[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# License Management
> mmd.emoticon=`tree`


## 라이선스 발급

### 고객관리

#### 식별코드, 이름, 연락처

#### 영업 담당자

### 라이선스 정보

#### 라이선스 타입

#### 유효 서비스

#### 하드웨어 정보

#### 만료일

#### 라이선스 서명

### 발급자 관리

#### 식별코드, 이름, 부서, 연락처

### 라이선스 관리

#### 라이선스 타입

##### 정규 라이선스\(Perpetual\)

##### 구독 라이선스 \(Subscription\)

##### 평가판 \(Evaluation/Trial\)

##### NFR \(Not For Resale\)

##### 아카데미

##### Ultimate

#### 서비스 종류

##### Openstackit, SE Cloudit, TabCloudit, DevOpsIt

#### 하드웨어 정보

##### IP, MAC, MB Serial

##### CPU : Socket, Core

#### 만료처리

#### 발급기록 관리

##### 라이선스, 발급자, 발급일자, 만료일자

### 키관리

#### 서명코드 관리

##### 생성, 삭제, 만료 처리

#### 암호화 코드관리

##### 생성, 삭제, 만료 처리

#### 오프라인 키관리 방법

## 라이선스 검증
> leftSide=`true`


### 검증방법

#### 온라인

##### 서비스, 하드웨어 식별정보, 라이선스 유효성

#### 오프라인

##### 복호화, 서명검증키 처리방안\.\.?

##### 서비스 식별 및 유효성 검증

### 검증방식

#### 서비스 검증

#### 하드웨어 검증
